"""
常量定义
"""

# 表名常量
TABLE_NATURAL_PERSON = "natural_person"
TABLE_INSTITUTION = "institution"
TABLE_PROJECT = "project"
TABLE_PRODUCT = "product"
TABLE_DOCTOR = "doctor"

# 客户等级
CUSTOMER_LEVEL_NORMAL = "普通会员"
CUSTOMER_LEVEL_SILVER = "银卡会员"
CUSTOMER_LEVEL_GOLD = "金卡会员"
CUSTOMER_LEVEL_PLATINUM = "铂金会员"
CUSTOMER_LEVEL_DIAMOND = "钻石会员"

# 项目类别
PROJECT_CATEGORY_SKIN_CARE = "皮肤护理"
PROJECT_CATEGORY_INJECTION = "注射美容"
PROJECT_CATEGORY_SURGERY = "手术美容"
PROJECT_CATEGORY_ANTI_AGING = "抗衰老"
PROJECT_CATEGORY_BODY_SHAPING = "美体塑形"

# 产品类别
PRODUCT_CATEGORY_COSMETICS = "化妆品"
PRODUCT_CATEGORY_INSTRUMENT = "仪器设备"
PRODUCT_CATEGORY_MEDICINE = "药品"
PRODUCT_CATEGORY_SUPPLEMENT = "营养补充剂"

# 咨询类型
CONSULTATION_TYPE_ONLINE = "online"
CONSULTATION_TYPE_OFFLINE = "offline"